polls/mypoll/urls.py
from django.urls import path

from . import views

app_name = 'mypoll'
urlpatterns =[
    path('', views.index,name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mypoll/', include('mypoll.urls')),
]

polls/mypoll/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.


# Question Model
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.question_text
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)


# Choice Model
class Choice(models.Model):
    question =models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text
    def __str__(self):
        return self.choice_text

polls/mypoll/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404
from django.template import loader
from .models import Question
from .models import Choice


# Create your views here.
def index (request):
    question_array =Question.objects.order_by('-pub_date')[:5]

    context = {
        'title' :'Poll Questions',
        'data' : question_array
    }
    return render(request, 'mypoll/index.html',context)


def test (request):
    return HttpResponse('Hello from myPoll APP--TEST VIEW!')


# THE DETAILS PAGE OF A SPECIFIC POLL
def detail(request, question_id):
    try:
        # GETTING THE QUESTION FOR THE PQN
       
        question = get_object_or_404(Question, pk=question_id)
     
        
        
        
    except Question.DoesNotExit:
        raise Http404("Question does not exits")
    context ={
        'question' :question,
       
    }
        
    #return HttpResponse("You're looking at question %s." % question_id)
    return render(request, 'mypoll/details.html',context)



def results(request, question_id):
    response ="You're looking at the results of question %s."
    return HttpResponse(response % question_id)
def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls/mypoll/templates/mypoll/details.html
{% extends 'mypoll/layout.html'%}


{% block content%}
<h3>Detail Page</h3>
<h1>{{question.question_text}}</h1>


{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'mypoll:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{
    ˓→choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" class="btn" value="Vote">
    </form>
<p></p>
<button class="btn"><a href="/mypoll">GO BAck</a></button>

{%endblock%}

polls/mypoll/templates/mypoll/index.html
{% extends 'mypoll/layout.html'%}

{% block content%}
  <h3 class="center-align red lighten-3">{{title}}</h3>
{% if data %}
<ul class="collection">
    {% for question in data %}

    <li class="collection-item"><a href="{% url 'mypoll:detail' question.id%}">{{question.question_text}}</a></li>
  
    {% endfor %}


</ul>
{% else %}
 <p>No polls are available</p>
{% endif %}
  
{% endblock %} 

polls/mypoll/templates/mypoll/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

     <!-- Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
             
    <title>myPoll App</title>
</head>
<body>
    <header class="container center-align">
        <h1>myPoll APP</h1>
    </header>
  <div class="container">
      {% block content %}
      {% endblock %}

  </div>
</body>
</html>